fix: hard to read counter
catppuccin/element pull request #6
Opened 2024-05-27 22:05 UTC by isabelroses

closes https://github.com/catppuccin/element/issues/4

2024-05-27 22:08 UTC, uncenter requested changes
The themes should not be in templates/...

2024-05-27 22:13 UTC, isabelroses commented
ohhh, i build in the `templates` dir

2024-05-27 22:16 UTC, uncenter approved these changes

2024-08-08 10:00 UTC, sgoudham approved these changes

2024-08-08 10:00 UTC, merged